---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf4-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
    }
    cpu {
      main-core 32
      corelist-workers 33
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }
