---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-controller-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
     - "172.17.0.1:22379"

  sfc.conf: |
    sfc_controller_config_version: 1
    description: Demo topology using bd and l2fibs
    host_entities:
        - name: vswitch
    sfc_entities:
        - name: vswitch-89-0-l2fib
          description: vswitch-89-0-l2fib - memif
          type: 3
          elements:
              - container: vswitch
                port_label: FortyGigabitEthernet89/0/0
                l2fib_macs:
                  - "02:00:00:89:00:AA"
                  - "02:00:00:89:00:BB"
                  - "02:00:00:89:00:CC"
                  - "02:00:00:89:00:DD"
                etcd_vpp_switch_key: vswitch
                type: 5
              - container: vnf1
                port_label: port1
                etcd_vpp_switch_key: vswitch
                l2fib_macs:
                  - "02:00:00:89:01:AA"
                type: 2
              - container: vnf2
                port_label: port1
                l2fib_macs:
                  - "02:00:00:89:01:BB"
                etcd_vpp_switch_key: vswitch
                type: 2
              - container: vnf3
                port_label: port1
                l2fib_macs:
                  - "02:00:00:89:01:CC"
                etcd_vpp_switch_key: vswitch
                type: 2
              - container: vnf4
                port_label: port1
                l2fib_macs:
                  - "02:00:00:89:01:DD"
                etcd_vpp_switch_key: vswitch
                type: 2
        - name: vswitch-89-1-l2fib
          description: vswitch-89-1-l2fib - memif
          type: 3
          elements:
              - container: vswitch
                port_label: FortyGigabitEthernet89/0/1
                l2fib_macs:
                  - "02:00:00:89:01:AA"
                  - "02:00:00:89:01:BB"
                  - "02:00:00:89:01:CC"
                  - "02:00:00:89:01:DD"
                etcd_vpp_switch_key: vswitch
                type: 5
              - container: vnf1
                port_label: port2
                l2fib_macs:
                  - "02:00:00:89:00:AA"
                etcd_vpp_switch_key: vswitch
                type: 2
              - container: vnf2
                port_label: port2
                l2fib_macs:
                  - "02:00:00:89:00:BB"
                etcd_vpp_switch_key: vswitch
                type: 2
              - container: vnf3
                port_label: port2
                l2fib_macs:
                  - "02:00:00:89:00:CC"
                etcd_vpp_switch_key: vswitch
                type: 2
              - container: vnf4
                port_label: port2
                l2fib_macs:
                  - "02:00:00:89:00:DD"
                etcd_vpp_switch_key: vswitch
                type: 2
  vnf.conf: |
    vnf_plugin_config_version: 1
    description: l2xconn vnf ports on each vnf for perf testing
    vnf_entities:
      - name: vnf1
        container: vnf1
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf2
        container: vnf2
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf3
        container: vnf3
        l2xconnects:
          - port_labels:
            - port1
            - port2
      - name: vnf4
        container: vnf4
        l2xconnects:
          - port_labels:
            - port1
            - port2
