---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-controller-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
     - "172.17.0.1:22379"

  sfc.conf: |
    sfc_controller_config_version: 1
    description: Demo topology using bd and l2fibs
    host_entities:
        - name: vswitch
    sfc_entities:
        - name: vswitch-89-0-l2fib
          description: vswitch-89-0-l2fib - memif
          type: 3
          elements:
              - container: vswitch
                port_label: FortyGigabitEthernet89/0/0
                etcd_vpp_switch_key: vswitch
                mac_addr: "02:00:00:00:89:00"
                type: 5
              - container: vnf1
                port_label: port1
                mac_addr: "02:00:00:00:00:11"
                etcd_vpp_switch_key: vswitch
                type: 2
        - name: vswitch-89-1-l2fib
          description: vswitch-89-1-l2fib - memif
          type: 3
          elements:
              - container: vswitch
                port_label: FortyGigabitEthernet89/0/1
                mac_addr: "02:00:00:00:89:01"
                etcd_vpp_switch_key: vswitch
                type: 5
              - container: vnf1
                port_label: port2
                mac_addr: "02:00:00:00:00:12"
                etcd_vpp_switch_key: vswitch
                type: 2

  vnf.conf: |
    vnf_plugin_config_version: 1
    description: Demo VNF config
    vnf_entities:
      - name: vnf1
        container: vnf1
        l2xconnects:
          - port_labels:
            - port1
            - port2

